# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#

boards:
  - nice_nano

shields:
  left: hshs52_left
  right: hshs52_right

config:
  path: config

keymap: hshs52.keymap

# This tells the action to automatically include the ZMK-provided overlay
# for the nice_view display
default_shields:
  - nice_view
